run_path: runs/gpt2_wikitext
model: gpt2
overwrite: true
cleanup_ckpts: false

data:
  dataset: Salesforce/wikitext
  subset: wikitext-2-raw-v1
  split: "train[:4608]"
  chunk_length: 512

query:
  dataset: Salesforce/wikitext
  subset: wikitext-2-raw-v1
  split: "train[-4608:]"
  chunk_length: 512

distributed:
  nproc_per_node: 8

batch_size: 160
num_epochs: 4
lr_schedule:
  lr_scheduler_type: polynomial
  lr: 0.0008
  lr_start: 1e-6
  lr_end: 0.00008
  warmup_steps: 0.25

subset_strategy: random
wandb_project: magic
