run_path: runs/modula_experiment/modula
model: gpt2
overwrite: true

data:
  dataset: Salesforce/wikitext
  subset: wikitext-2-raw-v1
  split: "train[:4608]"
  chunk_length: 512

query:
  dataset: Salesforce/wikitext
  subset: wikitext-2-raw-v1
  split: "train[:4608]"
  chunk_length: 512

distributed:
  nproc_per_node: 4
  nnode: 1

batch_size: 64
num_epochs: 4

lr_schedule:
  lr_scheduler_type: polynomial
  lr: 0.0008
  lr_start: 1e-6
  lr_end: 0.00008
  warmup_steps: 0.25

# Only difference from baseline: normalize weight updates in the modular norm.
use_modula: true

wandb_project: magic
