run_path: runs/compare_pythia14m_smoke
model: EleutherAI/pythia-14m
overwrite: true

data:
  dataset: Salesforce/wikitext
  subset: wikitext-2-raw-v1
  split: "train[:128]"
  chunk_length: 128

query:
  dataset: Salesforce/wikitext
  subset: wikitext-2-raw-v1
  split: "train[-128:]"
  chunk_length: 128

distributed:
  nproc_per_node: 1

batch_size: 16
num_epochs: 1
seed: 42

num_subsets: 10
subset_strategy: random

lr_schedule:
  lr_scheduler_type: polynomial
  lr: 0.0008
  lr_start: 1.0e-6
  lr_end: 8.0e-5
  warmup_steps: 0.25
